permalink: /:year/:month/:title/
url: http://aimeiyan.me
highlighter: pygments
author: nancy
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
textile_ext:   textile
pygments: true
paginate: 24
